// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CloseSerial(): $CancellablePromise<void> {
    return $Call.ByID(3369432026);
}

export function GetSerialPorts(): $CancellablePromise<string[]> {
    return $Call.ByID(178245474).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenSerial(portName: string, baudRate: number, dataBits: number, stopBits: number): $CancellablePromise<void> {
    return $Call.ByID(1859564582, portName, baudRate, dataBits, stopBits);
}

export function SendData(data: string): $CancellablePromise<void> {
    return $Call.ByID(2239076048, data);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
